# TODO fill this in for keycloak

location /auth {
  add_header Content-Type text/plain;
  return 200 'Keycloak\n';
}

# Keycloak
location /keycloak {
  # doesn't use nginx_auth_rt as it does its own auth directly
  proxy_pass http://keycloak;
  proxy_redirect off;
  proxy_set_header Host               keycloak.malcolm.local;
  proxy_set_header X-Real-IP          $remote_addr;
  proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host   $http_host;
  proxy_set_header X-Forwarded-Server $http_host;
  proxy_set_header X-Forwarded-Port   $server_port;
  proxy_set_header X-Forwarded-Proto  $http_x_forwarded_proto;
}
