location = /auth/redirect {
    access_by_lua_block {
        local opts = {
            redirect_uri_path = os.getenv("KEYCLOAK_AUTH_REDIRECT_URI"),
            discovery = os.getenv("KEYCLOAK_AUTH_URL") .. "/realms/" .. os.getenv("KEYCLOAK_AUTH_REALM") .. "/.well-known/openid-configuration",
            client_id = os.getenv("KEYCLOAK_CLIENT_ID"),
            client_secret = os.getenv("KEYCLOAK_CLIENT_SECRET"),
            session_contents = {id_token=true, access_token=true},
            ssl_verify = "no"
        }
        local res, err = require("resty.openidc").authenticate(opts)
        if err then
            ngx.status = 500
            ngx.log(ngx.ERR, "Error during callback: " .. err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
        end

        local session = require("resty.session").start()
        session:set("subject", res.id_token.sub)
        session:set("username", res.id_token.preferred_username)
        session:set("name", res.id_token.name or "")
        session:set("audience", res.id_token.aud or "")
        session:set("email", res.id_token.email or "")
        session:set("groups", res.id_token.groups or {})
        session:set("roles", res.id_token.roles or {})
        session:save()
    }
}
