location /auth {
  proxy_pass http://htadmin;
  proxy_redirect off;
  proxy_set_header Accept-Encoding "";
  proxy_set_header Host htadmin.malcolm.local;
  rewrite ^/auth/?(.*) /$1 break;
  subs_filter_types '*';
  subs_filter '(src|action|href)="([\w\.-]+\.(php|css|js))' '$1="/auth/$2' gir;
  subs_filter 'href="styles/' 'href="/auth/styles/' gi;
  subs_filter 'src="script/' 'src="/auth/script/' gi;
  subs_filter '/fonts/glyphicons' '/auth/fonts/glyphicons' gi;
}
location ~* ^/(htadmin|admin_login)(\.php)\b(.*) {
  proxy_pass http://htadmin/$1$2$3;
  proxy_redirect off;
  proxy_set_header Accept-Encoding "";
  proxy_set_header Host htadmin.malcolm.local;
  subs_filter_types '*';
  subs_filter '(src|action|href)="([\w\.-]+\.(php|css|js))' '$1="/auth/$2' gir;
  subs_filter 'href="styles/' 'href="/auth/styles/' gi;
  subs_filter 'src="script/' 'src="/auth/script/' gi;
  subs_filter '/fonts/glyphicons' '/auth/fonts/glyphicons' gi;
}
