filter {


  ################################################################################################
  # Do enrichment based on OTKB lookups

  ruby {
    id => "ruby_otkb_enrich"
    tag_on_exception => "_otkb_enrich"
    path => "/usr/share/logstash/malcolm-ruby/otkb_enrich.rb"
    script_params => {
        "enabled_env" => "OTKB_ENRICHMENT"
        "otkb_url_env" => "OTKB_URL"
        "otkb_token_env" => "OTKB_TOKEN"
        "cache_ttl_env" => "OTKB_ENRICHMENT_TTL"
        "ssl_verify_env" => "OTKB_SSL_VERIFY"
        "debug_env" => "OTKB_ENRICHMENT_DEBUG"
        "debug_timings_env" => "OTKB_ENRICHMENT_DEBUG_TIMINGS"
    }
  }

} # filter
