name: api-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'api/**'
      - 'Dockerfiles/api.Dockerfile'
      - 'shared/bin/*'
      - '!shared/bin/capa-build.sh'
      - '!shared/bin/common-init.sh'
      - '!shared/bin/tx-rx-secure.sh'
      - '!shared/bin/os-disk-config.py'
      - '!shared/bin/extracted_files_http_server.py'
      - '!shared/bin/pcap_processor.py'
      - '!shared/bin/web-ui-asset-download.sh'
      - '!shared/bin/preseed_late_user_config.sh'
      - '!shared/bin/configure-interfaces.py'
      - '!shared/bin/suricata*'
      - '!shared/bin/zeek*'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: api
      dockerfile: ./Dockerfiles/api.Dockerfile
