name: arkime-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
      - installer-staging
    paths:
      - 'arkime/**'
      - 'Dockerfiles/arkime.Dockerfile'
      - 'shared/bin/*'
      - '!shared/bin/capa-build.sh'
      - '!shared/bin/common-init.sh'
      - '!shared/bin/tx-rx-secure.sh'
      - '!shared/bin/extracted_files_http_server.py'
      - '!shared/bin/web-ui-asset-download.sh'
      - '!shared/bin/os-disk-config.py'
      - '!shared/bin/preseed_late_user_config.sh'
      - '!shared/bin/configure-interfaces.py'
      - '!shared/bin/suricata*'
      - '!shared/bin/zeek*'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: arkime
      dockerfile: ./Dockerfiles/arkime.Dockerfile
    secrets:
      maxmind_license_key: ${{ secrets.MAXMIND_GEOIP_DB_LICENSE_KEY }}
      maxmind_alternate_url: ${{ secrets.MAXMIND_GEOIP_DB_ALTERNATE_DOWNLOAD_URL }}
