name: file-monitor-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'file-monitor/**'
      - 'Dockerfiles/file-monitor.Dockerfile'
      - 'shared/bin/*'
      - '!shared/bin/common-init.sh'
      - '!shared/bin/tx-rx-secure.sh'
      - '!shared/bin/os-disk-config.py'
      - '!shared/bin/preseed_late_user_config.sh'
      - '!shared/bin/configure-interfaces.py'
      - '!shared/bin/suricata*'
      - '!shared/bin/zeek*.sh'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: file-monitor
      dockerfile: ./Dockerfiles/file-monitor.Dockerfile
