name: zeek-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
      - installer-staging
    paths:
      - 'zeek/**'
      - 'Dockerfiles/zeek.Dockerfile'
      - 'shared/bin/*'
      - '!shared/bin/capa-build.sh'
      - '!shared/bin/common-init.sh'
      - '!shared/bin/tx-rx-secure.sh'
      - '!shared/bin/os-disk-config.py'
      - '!shared/bin/extracted_files_http_server.py'
      - '!shared/bin/web-ui-asset-download.sh'
      - '!shared/bin/preseed_late_user_config.sh'
      - '!shared/bin/configure-interfaces.py'
      - '!shared/bin/suricata*'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: zeek
      dockerfile: ./Dockerfiles/zeek.Dockerfile
      extra_build_args: |
        BUILD_JOBS=2
    secrets:
      zeek_deb_alternate_download_url: ${{ secrets.ZEEK_DEB_ALTERNATE_DOWNLOAD_URL }}
